### ISSUE TITLE
Data stream encryption/decryption

### ISSUE THREAD

**Issue by sbucsc** [onelogin/aead#1]
It would be nice to extend the API and support the encryption/decryption of data streams. This would allow the gem to be used for encrypting/decrypting bigger data without the need to buffering the data in memory.

Thanks,
N

**Comment by stouset** [comment]
I agree. I'm reimagining the API for this, and considering basing it off of DJB's [NaCl](http://nacl.cr.yp.to), so as not to require extending the Ruby OpenSSL implementation.

**Comment by sbucsc** [comment]
Keeping it based on OpenSSL would keeps the developers decision much easier. OpenSSL is a de facto standard toolkit trusted for cryptography between developers and I believe that was the main idea behind ruby depending on OpenSSL instead of building their own crypto library. What are your concerns continuing with OpenSSL? What advantages do you think is in switching to NaCI?

**Comment by stouset** [comment]
OpenSSL hasn't had the best track record regarding security, or code standards and quality. Support for true AEAD modes like GCM has only come in the past half-year or so, and any developers using a Mac require compiling a newer version of OpenSSL, and custom-compiling Ruby to link against it.

DJB's NaCl is small, focused, follows tight coding standards that avoid common pitfalls like leaking timing information, and is written and maintained by one of the world's most prominent cryptographers. It can be easily bundled with the gem, and provides high-level interfaces to prevent developers from shooting themselves in the foot (as much as is possible).

**Comment by stouset** [comment]
Also, I looked into supporting a streaming-style API, and realized that this is fundamentally incompatible with AEAD modes of encryption. It's not safe to release plaintexts to the caller before the authenticator is verified, and this requires access to the entire cryptostream. [From the horse's mouth](https://twitter.com/hashbreaker/status/289234463311925249).

**Comment by sbucsc** [comment]
Correct! OpenSSL has had quite a few vulnerabilities in the past, though I am off the opinion that this is not necessarily only a negative thing. It could be an indicator for how much attention this library is getting from the community and how closely its security has been investigated. I am not very familiar with DJB's NaCI library and I don't know really know how it is being maintained. I believe that one major factor that makes a crypto library reliable and trustworthy is its developer and users community. 

The point about streaming-style API is a very valid point actually and the more I think about it it makes more sense. It remind me of how SSL/TLS packets are designed and a separate MAC is attached to each packet and verified per packet. So, after all you think leaving out streaming API is the way to go?

**Comment by stouset** [comment]
I should have replied to this sooner, but somehow completely missed the email notification.

You're right that OpenSSL has a lot of developer attention, but DJB's NaCl has a few significant advantages:
- it's designed to be high-level, instead of working with cryptographic primitives directly
- it's extremely focused, rather than implementing every algorithm and protocol under the sun (less code means fewer opportunities for bugs)
- it obeys strict [coding guidelines](http://nacl.cr.yp.to/internals.html) to avoid classes of attacks, rather than playing whack-a-mole with vulnerabilities
- it's authored and maintained by a cryptographer with a strong track record of writing extremely secure software

To the first point, using OpenSSL requires that I work directly with cryptographic primitives. As a non-cryptographer, working at this level is _extremely dangerous_ (I'm giving a [talk on exactly this](http://www.sfruby.info/events/99087412/) in February). It's like building a car engine from parts: you're overwhelmingly likely to miss one tiny detail and have the whole thing explode in your face.

**Comment by stouset** [comment]
To your other question, I think I'm forced to consider a streaming API out of the question. I briefly considered feigning a streaming API by just chunking the data and passing chunks to an AEAD cipher, but there are a few significant problems.

First, this would require generating lots of IVs, increasing the size of the data considerably. Second, and more importantly, I am not a cryptographer and this is in a very real sense implementing my own cryptography. It's important, as DJB noted, that plaintext is not released before verifying the authenticator; this may very well imply that it's necessary to verify the _whole_ ciphertext before releasing _any_ of the plaintext. This is, of course, wholly incompatible with a streaming approach.

I posted a question about this to the [crypto Stack Exchange](http://crypto.stackexchange.com/questions/6008/streaming-api-to-authenticated-encryption). I wouldn't implement this myself, but it's an interesting problem nonetheless.
